name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-check:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check PHP syntax
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l
